DROP DATABASE IF EXISTS INFLUWEB;
CREATE DATABASE INFLUWEB;
USE INFLUWEB;

CREATE TABLE USUARIOS
(
	USER_ID INT AUTO_INCREMENT NOT NULL,
	USER_EMAIL VARCHAR(250) NULL,
	USER_PASSWORD VARCHAR(250) NULL,
	USER_NAME VARCHAR(250) NULL,
	USER_USER VARCHAR(250) NULL,
	PROFILE_PICTURE VARCHAR(250) NULL,
	USER_ADMIN BOOLEAN NULL,
	PRIMARY KEY(USER_ID)
);
INSERT INTO `USUARIOS` (`USER_ID`, `USER_EMAIL`, `USER_PASSWORD`, `USER_ADMIN`) VALUES
(1, 'admin@influweb.com', '6216f8a75fd5bb3d5f22b6f9958cdede3fc086c2', 1);
-- Credenciales de admin. Email: admin@influweb.com, Password: 111 

CREATE TABLE INFLUENCER
(
	NOMBRE_INFLUENCER VARCHAR(250) NULL,
	LOGO_INFLUENCER VARCHAR(250) NULL,
	SLOGAN_INFLUENCER VARCHAR(250) NULL,
	COLOR1_INFLUENCER VARCHAR(250) NULL,
	COLOR2_INFLUENCER VARCHAR(250) NULL,
	BACKGROUND_INFLUENCER VARCHAR(250) NULL,
	URL_INSTAGRAM VARCHAR(250) NULL,
	URL_FACEBOOK VARCHAR(250) NULL,
	URL_TWITTER VARCHAR(250) NULL,
	PRIMARY KEY(NOMBRE_INFLUENCER)
);

CREATE TABLE INFLUENCER_CONTENIDOS
(
    CONTENIDO_ID INT AUTO_INCREMENT NOT NULL,
	CONTENIDO_TITULO VARCHAR(250) NULL,
    CONTENIDO_TEXTO VARCHAR(250) NULL,
    CONTENIDO_TIPO INT NULL CHECK (CONTENIDO_TIPO >= 1 AND CONTENIDO_TIPO <= 3),
	PRIMARY KEY(CONTENIDO_ID)
);


CREATE TABLE EVENTOS_CALENDARIO
(
	EVENTO_ID INT AUTO_INCREMENT NOT NULL,
	EVENTO_PICTURE VARCHAR(250) NULL,
	EVENTO_STATUS BOOLEAN NULL,
	EVENTO_TEXT VARCHAR(250) NULL,
	EVENTO_DATE_INI DATETIME NULL,
	EVENTO_DATE_FIN DATETIME NULL,
	PRIMARY KEY(EVENTO_ID)
);

CREATE TABLE SPONSORS
(
	EMPRESA_ID INT AUTO_INCREMENT NOT NULL,
	EMPRESA_PICTURE VARCHAR(250) NULL,
	EMPRESA_NAME VARCHAR(250) NULL,
	EMPRESA_INFO VARCHAR(250) NULL,
	EMPRESA_URL VARCHAR(250) NULL,
	PRIMARY KEY(EMPRESA_ID)
);

CREATE TABLE PRODUCTOS (
    PRODUCTO_ID INT AUTO_INCREMENT NOT NULL,
    PRODUCTO_PICTURE VARCHAR(250) NULL,
    PRODUCTO_NAME VARCHAR(250) NULL,
    PRODUCTO_INFO VARCHAR(250) NULL,
    PRODUCTO_PRECIO INT NULL,
    PRODUCTO_STOCK INT NULL,
    EMPRESA_ID INT NULL,
    PRIMARY KEY (PRODUCTO_ID),
    FOREIGN KEY (EMPRESA_ID) REFERENCES SPONSORS (EMPRESA_ID)
);